# version: '3.8'

services:
  redis:
    image: redis
    container_name: mohith-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mohith-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mohith-network

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7475:7475"
      - "7689:7689"
    environment:
      - NEO4J_AUTH=neo4j/password12345 
    networks:
      - mohith-network

  qdrant:
    image: qdrant/qdrant
    container_name: mohith-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mohith-network

  
  market-data-service:
    build: ./services/market-data-service
    container_name: market-data-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mohith-network

  realtime-gateway:
    build: ./services/realtime_gateway
    container_name: realtime-gateway
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - mohith-network
    environment:
      - REDIS_HOST=redis

  alerts-service:
    build: ./services/anomaly_detection_service
    container_name: alerts-service
    ports:
      - "8002:8002"
    networks:
      - mohith-network

  watchlist-service:
    build: ./services/watchlist_service
    container_name: watchlist-service
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    networks:
      - mohith-network

  stockrelation-service:
    build: ./services/stockRelation_service
    container_name: stockrelation-service
    ports:
      - "8004:8004"
    depends_on:
      - neo4j
    networks:
      - mohith-network

  ai-chatbot-service:
    build:
      context: ./services/AI-chatbot-service/app
    container_name: ai-chatbot-service
    ports:
      - "8008:8008"
    depends_on:
      - redis
      - qdrant
    env_file:
      - ./services/AI-chatbot-service/app/.env
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mohith-network

  graph-service:
    build: ./services/graph-service/data_ingestion
    container_name: graph-service
    ports:
      - "8012:8012"
    depends_on:
      - mongo
      - neo4j
    networks:
      - mohith-network

  trending-service:
    build: ./services/trending-service/app
    container_name: trending-service
    ports:
      - "8010:8010"
    depends_on:
      - neo4j
    networks:
      - mohith-network

networks:
  mohith-network:

volumes:
  redis_data:
  qdrant_data:
