# version: "3.8"

services:
  graph-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graph-service
    depends_on:
      - redis
      - mongodb
      - neo4j
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
